# Generated by Django 5.2.7 on 2025-10-30 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('indicator_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('hash', 'File Hash'), ('url', 'URL'), ('malware', 'Malware Family'), ('campaign', 'Campaign / Actor')], max_length=50)),
                ('severity', models.IntegerField(default=1)),
                ('confidence', models.IntegerField(default=50)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intel_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen', '-created_at'],
            },
        ),
    ]
