# Generated by Django 5.2.7 on 2025-10-16 06:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=512, unique=True)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('url', 'URL'), ('sha256', 'SHA256')], max_length=16)),
                ('verdict', models.CharField(default='unknown', max_length=16)),
                ('threat_score', models.FloatField(default=0.0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalIOC',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=512)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('url', 'URL'), ('sha256', 'SHA256')], max_length=16)),
                ('verdict', models.CharField(default='unknown', max_length=16)),
                ('threat_score', models.FloatField(default=0.0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, editable=False)),
                ('last_seen', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ioc',
                'verbose_name_plural': 'historical iocs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='ioc.ioc')),
            ],
        ),
    ]
