# Generated by Django 5.2.7 on 2025-10-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalioc',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='ioc',
            name='tags',
        ),
        migrations.AddField(
            model_name='ioc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='ioc_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='threat_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='verdict',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='Enrichment',
        ),
        migrations.DeleteModel(
            name='HistoricalIOC',
        ),
    ]
