# Generated by Django 5.2.7 on 2025-10-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0002_remove_historicalioc_history_user_remove_ioc_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
