# Generated by Django 5.2.7 on 2025-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATTCKTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('tactic', models.CharField(max_length=128)),
            ],
        ),
    ]
