# Generated by Django 5.2.7 on 2025-11-04 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(choices=[('indicator_type', 'Indicator Type'), ('severity', 'Severity'), ('confidence', 'Confidence'), ('case_status', 'Case Status'), ('intel_source', 'Intel Source'), ('tag', 'Tag')], db_index=True, max_length=32)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('vocab', 'order', 'label'),
                'unique_together': {('vocab', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='ATTCKTechnique',
        ),
    ]
