# Generated by Django 5.2.7 on 2025-11-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_savedsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTIEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('source', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('source_system', models.CharField(max_length=128)),
                ('rule_id', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=28)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('mitre_url', models.URLField(blank=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='techniques', to='taxonomy.tactic')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField()),
                ('cti_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.ctievent')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.technique')),
            ],
            options={
                'unique_together': {('technique', 'cti_event')},
            },
        ),
        migrations.CreateModel(
            name='TechniqueStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sightings_7d', models.PositiveIntegerField(default=0)),
                ('sightings_30d', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('coverage_score', models.FloatField(default=0.0)),
                ('last_coverage_sync', models.DateTimeField(blank=True, null=True)),
                ('technique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='taxonomy.technique')),
            ],
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='owner',
        ),
        migrations.DeleteModel(
            name='TaxonomyTerm',
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_rules', to='taxonomy.technique'),
        ),
        migrations.AddField(
            model_name='ctievent',
            name='techniques',
            field=models.ManyToManyField(related_name='cti_events', through='taxonomy.TechniqueSighting', to='taxonomy.technique'),
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
    ]
