# Generated by Django 5.2.7 on 2025-11-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_ctievent_detectionrule_tactic_technique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('vocab', 'order', 'key'),
                'unique_together': {('vocab', 'key')},
            },
        ),
    ]
